name = "tsuka-typing-backend"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "tsuka-typing-db"
database_id = "00bba5e7-c937-422b-a07b-86664e12fbbe"

[vars]
CORS_ORIGIN = "https://tsuka-typing.tsukasa-kingdom.net"
